#include "colors.h"

const int egaColors[16] = {BLACK, BLUE, GREEN, CYAN, RED, MAGENTA, YELLOW, LIGHT_GREY, DARK_GREY, BRIGHT_BLUE, BRIGHT_GREEN, BRIGHT_CYAN, BRIGHT_RED, BRIGHT_MAGENTA, BRIGHT_YELLOW, WHITE};
